[manager]
show_hidden = true

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.prepend_previewers]]
mime = "application/x-bittorrent"
run = "torrent-preview"

[[plugin.prepend_previewers]]
name = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.ipynb"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.json"
run = "rich-preview"
